buildscript {
    ext {
        creds = {
            username = findProperty("github.user") ?: System.getenv("GITHUB_ACTOR")
            password = findProperty("github.token") ?: System.getenv("GITHUB_TOKEN")
        }
    }
    repositories {
        mavenCentral()
        maven {
            url uri("https://maven.pkg.github.com/trevorism/gradle-release-plugin")
            credentials creds
        }
    }
    dependencies {
        classpath 'com.trevorism:gradle-release-plugin:0.7.0'
    }
}

plugins{
    id("io.micronaut.library") version "5.0.0"
    id "jacoco"
}

apply plugin: "com.trevorism.gradle.release"

repositories {
    mavenCentral()
    maven {
        url uri("https://maven.pkg.github.com/trevorism/secure-utils")
        credentials creds
    }
}

micronaut{
    version = "5.0.2"
    importMicronautPlatform = false
}

dependencies {
    api 'com.trevorism:secure-utils:6.0.0'

    annotationProcessor 'io.micronaut:micronaut-inject-java:5.0.2'
    annotationProcessor 'io.micronaut:micronaut-graal:5.0.2'
    annotationProcessor 'io.micronaut.security:micronaut-security-annotations:5.0.0'
    testAnnotationProcessor 'io.micronaut:micronaut-inject-java:5.0.2'
    testAnnotationProcessor 'io.micronaut:micronaut-graal:5.0.2'
    testAnnotationProcessor 'io.micronaut.security:micronaut-security-annotations:5.0.0'

    implementation 'io.micronaut.security:micronaut-security:5.0.0'
    implementation 'io.micronaut:micronaut-http:5.0.2'
    implementation "io.micronaut:micronaut-router:5.0.2"

    implementation 'io.projectreactor:reactor-core:3.8.5'
    implementation 'jakarta.inject:jakarta.inject-api:2.0.1'

    implementation 'ch.qos.logback:logback-classic:1.5.34'

    testImplementation 'io.projectreactor:reactor-test:3.8.5'
    testImplementation(platform("org.junit:junit-bom:6.1.0"))
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}